# Generated by Django 4.2.19 on 2025-02-24 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("estimate_end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("progress", "Progress"),
                            ("done", "Done"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Chi phí dự kiến (VND)",
                        max_digits=20,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Tổng chi phí (VND)",
                        max_digits=20,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                (
                    "debt_amount",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                ("purchased_date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
