# Generated by Django 4.2.19 on 2025-02-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="customer_name",
        ),
        migrations.AddField(
            model_name="material",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=512, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="unit",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="customer_gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=512, null=True, unique=True
            ),
        ),
    ]
