# Generated by Django 4.2.19 on 2025-02-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0002_rename_name_project_customer_name_material_slug_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="debt_amount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="paid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Tổng chi phí (VND)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_estimated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Chi phí dự kiến (VND)",
                max_digits=20,
                null=True,
            ),
        ),
    ]
